# Files in this package (stcmgtool.units) are distributed under separate terms —
# see NOTICE.txt in this directory. They are NOT covered by the project's MIT
# License.

from sctmgtool.base import Unit, Faction, Speed, Tag, Weapon, Squad, Range, Upgrade, SurgeDie, Cost, Hook

ZERG_UNITS: tuple[Unit] = (
    Unit(
        faction=Faction.Zerg,
        name="Corpser (Roach)",
        shield=None,
        speed=Speed(4, 7),
        evade=5,
        armour=3,
        hit_points=4,
        weapons=(
            Weapon("Acid Saliva", 8, Tag.Ground, 2, 3, None, None, 1),
            Weapon("Claws", "E", Tag.Ground, 3, 4, Tag.Light, SurgeDie.D3P1, 1),
            Weapon("Devastating Charge", "C", Tag.Ground, 3, 4, None, None, 1),
        ),
        squad=(Squad(Range(2, 3), 1, 240),),
        tags=Tag.Biological | Tag.Armoured | Tag.Ground,
        upgrades=(
            Upgrade(
                "Hydriodic Bile",
                cost=Cost(10),
                message="This Unit's Acid Saliva weapon gains Surge Type: Light, and S Dice: D3+1.",
                apply=lambda unit: unit.weapon("Acid Saliva").set_surge_die(SurgeDie.D3P1) or unit.weapon("Acid Saliva").add_surge_tag(Tag.Light),
            ),
            Upgrade("Burrow", upgrade_type=Upgrade.Type.Other),
            Upgrade("Tunneling Claws", upgrade_type=Upgrade.Type.Other),
            Upgrade("Roachling Infestation", upgrade_type=Upgrade.Type.Other),
            Upgrade("Burrow Ambush", upgrade_type=Upgrade.Type.Other),
            Upgrade("Glial Reconstitution", upgrade_type=Upgrade.Type.Other),
            Upgrade("Regeneration", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Hydralisk",
        shield=None,
        speed=Speed(4, 8),
        evade=5,
        armour=5,
        hit_points=4,
        weapons=(
            Weapon("Needle Spines", 12, Tag.Ground | Tag.Flying, 3, 3, Tag.Light | Tag.Armoured, SurgeDie.D3P1, 2),
            Weapon("Scythe", "E", Tag.Ground, 2, 4, None, None, 1),
        ),
        squad=(
            Squad(Range(2, 2), 2, 140),
            Squad(Range(3, 4), 3, 260),
        ),
        tags=Tag.Biological | Tag.Light | Tag.Ground,
        upgrades=(
            Upgrade(
                "Ancillary Carapace",
                cost=Cost(20, 40),
                message="This Unit gains TOUGH (1) on the first Armour Roll of each Activation.",
                apply=lambda unit: unit.add_tag(Tag.Tough1),
            ),
            Upgrade(
                "Lurking",
                cost=Cost(10, 20),
                message="If this Unit has Stationary Status, it is eligible to make an Evade Roll against the first Ranged Attack targeting it this Round.",
                apply=lambda unit: unit.grant_reroll("R"),
            ),
            Upgrade(
                "! Lurking + ON CREEP", message="If this Unit is ON CREEP, it gains +1 Modifier to this Evade Roll.", apply=lambda unit: unit.buff_evade(1)
            ),
            Upgrade("Squadron", upgrade_type=Upgrade.Type.Other),
            Upgrade("Burrow Ambush", upgrade_type=Upgrade.Type.Other),
            Upgrade("Lunge", upgrade_type=Upgrade.Type.Other),
            Upgrade("Grooved Spines", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Kerrigan",
        shield=None,
        speed=Speed(7, 7),
        evade=6,
        armour=5,
        hit_points=9,
        weapons=(
            Weapon("Energy Blast", 8, Tag.Ground | Tag.Flying, 5, 3, Tag.Light | Tag.Armoured, SurgeDie.D3, 1),
            Weapon("Blades", "E", Tag.Ground, 6, 4, None, None, 2, tags=Tag.CriticalHit2),
            Weapon("Devastating Charge", "C", Tag.Ground, 4, 4, None, None, 1),
        ),
        squad=(Squad(Range(1, 1), 1, 250),),
        tags=Tag.Biological | Tag.Psionic | Tag.Ground | Tag.Unique,
        upgrades=(
            Upgrade(
                "Mutating Carapace",
                cost=Cost(points=1),
                message='Select one Enemy Unit Within 18". This Unit is eligible to make an Evade Roll against all attacks made by the selected Enemy Unit, with a +2 Modifier applied to those Evade Rolls.',
                apply=lambda unit: unit.grant_reroll("REC") or unit.buff_evade(2),
            ),
            Upgrade("Commander", upgrade_type=Upgrade.Type.Other),
            Upgrade("Crushing Grip", upgrade_type=Upgrade.Type.Other),
            Upgrade("Leaping Strike", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Kerrigan Swarm Raptor (Zergling)",
        shield=None,
        speed=Speed(5, 9),
        evade=4,
        armour=5,
        hit_points=2,
        weapons=(
            Weapon("Claws", "E", Tag.Ground, 2, 3, Tag.Light | Tag.Armoured, SurgeDie.D6, 1, tags=Tag.Instant),
            Weapon("Devastating Charge", "C", Tag.Ground, 2, 5, None, None, 1),
        ),
        squad=(Squad(Range(4, 6), 1, 250),),
        tags=Tag.Biological | Tag.Light | Tag.Ground | Tag.Unique,
        upgrades=(
            Upgrade(
                "Adrenal Overload",
                cost=Cost(points=1),
                message="This Unit gains a +1 Modifier to all IMPACT Hit Rolls.",
                apply=lambda unit: unit.weapon("Devastating Charge").buff_hit(1),
            ),
            Upgrade("Squadron", upgrade_type=Upgrade.Type.Other),
            Upgrade("Raptor Strain", upgrade_type=Upgrade.Type.Other),
            Upgrade("Leap", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Omega Worm",
        shield=None,
        speed=Speed(0, 0),
        evade=None,
        armour=5,
        hit_points=10,
        weapons=(),
        squad=(Squad(Range(1, 1), 0, 0),),
        tags=Tag.Biological | Tag.Armoured | Tag.Ground,
        upgrades=(
            Upgrade("Detection", upgrade_type=Upgrade.Type.Other),
            Upgrade("Source of Creep", upgrade_type=Upgrade.Type.Other),
            Upgrade("Structure", upgrade_type=Upgrade.Type.Other),
            Upgrade("Omega Network", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Queen",
        shield=None,
        speed=Speed(4, 4),
        evade=None,
        armour=4,
        hit_points=9,
        weapons=(
            Weapon("Talons (Combat)", "E", Tag.Ground, 3, 4, None, None, 1),
            Weapon("Talons (Assault)", "6", Tag.Ground, 4, 4, Tag.Light, SurgeDie.D3, 2),
            # Note: Spines are not actually a "for" replacement
            Weapon("Acid spines", 12, Tag.Flying, 4, 4, Tag.Light | Tag.Armoured, SurgeDie.D3, 2, exchange_for="Talons (Assault)"),
            Weapon("Devastating Charge", "C", Tag.Ground, 4, 3, None, None, 1),
        ),
        squad=(Squad(Range(1, 1), 1, 150),),
        tags=Tag.Biological | Tag.Armoured | Tag.Ground | Tag.Psionic,
        upgrades=(
            Upgrade("Acid spines", apply=Upgrade.activate_weapon),
            Upgrade("Spawn Creep Tumor", upgrade_type=Upgrade.Type.Other),
            Upgrade("Transfusion", upgrade_type=Upgrade.Type.Other),
            Upgrade("Restoration", upgrade_type=Upgrade.Type.Other),
            Upgrade("Psionic Link", upgrade_type=Upgrade.Type.Other),
            Upgrade("Creep Speed", upgrade_type=Upgrade.Type.Other),
            Upgrade("Domineering Presence", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Raptor (Zergling)",
        shield=None,
        speed=Speed(5, 9),
        evade=4,
        armour=6,
        hit_points=1,
        weapons=(
            Weapon("Claws", "E", Tag.Ground, 2, 4, Tag.Light, SurgeDie.D3, 1),
            Weapon("Shredding Claws", "E", Tag.Ground, 2, 4, Tag.Light | Tag.Armoured, SurgeDie.D3, 1, exchange_for="Claws"),
            Weapon("Devastating Charge", "C", Tag.Ground, 1, 5, None, None, 1),
        ),
        squad=(
            Squad(Range(7, 12), 1, 240),
            Squad(Range(13, 18), 2, 300),
        ),
        tags=Tag.Biological | Tag.Light | Tag.Ground,
        upgrades=(
            Upgrade(
                "Adrenal Overload",
                cost=Cost(points=1),
                message="This Unit gains a +1 Modifier to all IMPACT Hit Rolls.",
                apply=lambda unit: unit.weapon("Devastating Charge").buff_hit(1),
            ),
            Upgrade(
                "Adrenal Glands",
                cost=Cost(20),
                message="This Unit’s Claws and Shredding Claws weapons gain PRECISION (2).",
                apply=lambda unit: unit.weapon(["Claws", "Shredding Claws"]).add_tag(Tag.Precision2),
            ),
            Upgrade("Shredding Claws", Upgrade.activate_weapon),
            Upgrade("Squadron", upgrade_type=Upgrade.Type.Other),
            Upgrade("Raptor Strain", upgrade_type=Upgrade.Type.Other),
            Upgrade("Burrow Ambush", upgrade_type=Upgrade.Type.Other),
            Upgrade("Metabolic Boost", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Roach",
        shield=None,
        speed=Speed(4, 7),
        evade=5,
        armour=3,
        hit_points=4,
        weapons=(
            Weapon("Claws", "E", Tag.Ground, 2, 4, None, None, 1),
            Weapon("Acid Saliva", 8, Tag.Ground, 3, 3, None, None, 1),
            Weapon("Devastating Charge", "C", Tag.Ground, 2, 4, None, None, 1),
        ),
        squad=(Squad(Range(2, 3), 1, 170),),
        tags=Tag.Biological | Tag.Armoured | Tag.Ground,
        upgrades=(
            Upgrade(
                "Hydriodic Bile",
                cost=Cost(10),
                message="This Unit's Acid Saliva weapon gains Surge Type: Light, and S Dice: D3+1.",
                apply=lambda unit: unit.weapon("Acid Saliva").set_surge_die(SurgeDie.D3P1) or unit.weapon("Acid Saliva").add_surge_tag(Tag.Light),
            ),
            Upgrade("Burrow", upgrade_type=Upgrade.Type.Other),
            Upgrade("Tunneling Claws", upgrade_type=Upgrade.Type.Other),
            Upgrade("Burrow Ambush", upgrade_type=Upgrade.Type.Other),
            Upgrade("Glial Reconstitution", upgrade_type=Upgrade.Type.Other),
            Upgrade("Regeneration", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Roachling",
        shield=None,
        speed=Speed(4, 7),
        evade=6,
        armour=6,
        hit_points=1,
        weapons=(Weapon("Claws", "E", Tag.Ground, 2, 4, None, None, 1),),
        squad=(Squad(Range(1, 3), 0, 0),),
        tags=Tag.Biological | Tag.Light | Tag.Ground,
        upgrades=(Upgrade("Underdeveloped Claws", upgrade_type=Upgrade.Type.Other),),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Swarmling (Zergling)",
        shield=None,
        speed=Speed(4, 8),
        evade=5,
        armour=6,
        hit_points=1,
        weapons=(
            Weapon("Claws", "E", Tag.Ground, 2, 5, None, None, 1),
            Weapon("Devastating Charge", "C", Tag.Ground, 1, 5, None, None, 1),
        ),
        squad=(Squad(Range(7, 18), 1, 260),),
        tags=Tag.Biological | Tag.Light | Tag.Ground,
        upgrades=(
            Upgrade("Squadron", upgrade_type=Upgrade.Type.Other),
            Upgrade("Burrow Ambush", upgrade_type=Upgrade.Type.Other),
            Upgrade("Zergling Reconstitution", upgrade_type=Upgrade.Type.Other),
            Upgrade("Metabolic Boost", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Vile (Roach)",
        shield=None,
        speed=Speed(4, 7),
        evade=5,
        armour=3,
        hit_points=4,
        weapons=(
            Weapon("Vile Claws", "E", Tag.Ground, 2, 4, None, None, 1),
            Weapon("Acid Saliva", 8, Tag.Ground, 4, 3, None, None, 1),
            Weapon("Devastating Charge", "C", Tag.Ground, 1, 4, None, None, 1),
        ),
        squad=(Squad(Range(2, 3), 1, 200),),
        tags=Tag.Biological | Tag.Armoured | Tag.Ground,
        upgrades=(
            Upgrade(
                "Hydriodic Bile",
                cost=Cost(10),
                message="This Unit's Acid Saliva weapon gains Surge Type: Light, and S Dice: D3+1.",
                apply=lambda unit: unit.weapon("Acid Saliva").set_surge_die(SurgeDie.D3P1) or unit.weapon("Acid Saliva").add_surge_tag(Tag.Light),
            ),
            Upgrade(
                "Debilitating Saliva",
                cost=Cost(points=1),
                message="Use when an Enemy Unit Within 8\" of this Unit declares a Ranged Attack. Apply DEBUFF Hit (1) to each of that Unit's Ranged Weapons.",
                apply={Hook.ModifyOpponent: lambda unit: unit.weapon("@type_letter==R").debuff_hit(1)},
                upgrade_type=Upgrade.Type.Defensive,
            ),
            Upgrade("Burrow", upgrade_type=Upgrade.Type.Other),
            Upgrade("Tunneling Claws", upgrade_type=Upgrade.Type.Other),
            Upgrade("Burrow Ambush", upgrade_type=Upgrade.Type.Other),
            Upgrade("Glial Reconstitution", upgrade_type=Upgrade.Type.Other),
            Upgrade("Regeneration", upgrade_type=Upgrade.Type.Other),
        ),
    ),
    Unit(
        faction=Faction.Zerg,
        name="Zergling",
        shield=None,
        speed=Speed(4, 8),
        evade=4,
        armour=6,
        hit_points=1,
        weapons=(
            Weapon("Claws", "E", Tag.Ground, 2, 4, Tag.Light, SurgeDie.D3, 1),
            Weapon("Shredding Claws", "E", Tag.Ground, 2, 4, Tag.Light | Tag.Armoured, SurgeDie.D3, 1, exchange_for="Claws"),
            Weapon("Devastating Charge", "C", Tag.Ground, 1, 5, None, None, 1),
        ),
        squad=(
            Squad(Range(7, 12), 1, 180),
            Squad(Range(13, 18), 2, 220),
        ),
        tags=Tag.Biological | Tag.Light | Tag.Ground,
        upgrades=(
            Upgrade(
                "Adrenal Glands",
                cost=Cost(20),
                message="This Unit’s Claws and Shredding Claws weapons gain PRECISION (2).",
                apply=lambda unit: unit.weapon(["Claws", "Shredding Claws"]).add_tag(Tag.Precision2),
            ),
            Upgrade("Shredding Claws", Upgrade.activate_weapon),
            Upgrade("Squadron", upgrade_type=Upgrade.Type.Other),
            Upgrade("Burrow Ambush", upgrade_type=Upgrade.Type.Other),
            Upgrade("Metabolic Boost", upgrade_type=Upgrade.Type.Other),
        ),
    ),
)
